name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: book-app

      - name: Build Angular app
        run: npm run build
        working-directory: book-app

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_MEADOW_0778E2103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # For PR comment automation
          action: "upload"
          #### CHANGE THIS TO MATCH SETUP:
          app_location: "book-app"
          api_location: ""  # Empty since we don't use Azure Functions here
          output_location: "dist/book-app"
