
name: Build and deploy Angular app to Azure Web App - testet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'


      - name: Install and build Angular app
        run: |
          cd frontend/book-quotes
          npm ci
          npm run build -- --configuration production

      - name: Zip build output for deployment
        run: |
          cd frontend/book-quotes/dist/book-quotes
          zip -r ../../../release.zip ./

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testet'
          slot-name: 'Production'
          package: .
